# Dataset
dataset: "CIFAR-10-LT" # "CIFAR-10-LT" or "CelebA-5"
train_transform_reprs:
- "ConvertImageDtype(float)"
- "RandomHorizontalFlip()"
- "RandomCrop(32, padding=4)"
- "Normalize((0.4988, 0.5040, 0.4926), (0.2498, 0.2480, 0.2718))"
valid_transform_reprs:
- "ConvertImageDtype(float)"
- "Normalize((0.4988, 0.5040, 0.4926), (0.2498, 0.2480, 0.2718))"

# DataLoader
num_workers: 8
batch_size: 128
enable_oversampling: False
oversampling_start_epoch: 160
oversample_majority_class_num_samples: True
oversample_use_effective_num_sample_weights: False

# Model
model: "ResNet-32-m2m" # "ResNet-32-m2m" or "ResNet-32-akamaster" or "WideResNet-28-10-torchdistill" or "WideResNet-28-10-xternalz"
dropout_rate: 0.3

# Optimizer
lr: 0.1
momentum: 0.9
weight_decay: 2.0e-4
lr_decay: 0.01
lr_decay_epochs: [160, 180]
enable_linear_warmup: False

# Logging
enable_wandb: False

# Checkpoint
enable_checkpoint: False
save_ckpt_every_n_epoch: 10
load_ckpt: False
load_ckpt_filepath: "checkpoints/.pt"
load_ckpt_epoch: 0

# Training
num_epochs: 200

# OPeN
enable_open: False
delta: 0.333333333333333333333333333333333333
pure_noise_mean: [0.4988, 0.5040, 0.4926]
pure_noise_std: [0.2498, 0.2480, 0.2718]
pure_noise_image_size: 32
open_start_epoch: 160

# Debugging
debug_run: False