# Dataset
dataset: "CIFAR-10-LT" # "CIFAR-10-LT" or "CelebA-5"
train_transform_reprs:
- "ConvertImageDtype(float)"
- "RandomCrop(32, padding=4)"
- "RandomHorizontalFlip()"
- "Normalize((0.4988, 0.5040, 0.4926), (0.2498, 0.2480, 0.2718))"
valid_transform_reprs:
- "ConvertImageDtype(float)"
- "Normalize((0.4988, 0.5040, 0.4926), (0.2498, 0.2480, 0.2718))"

# DataLoader
num_workers: 8
batch_size: 128
use_oversampling: False

# Model
model: "ResNet-32-m2m" # "ResNet-32-m2m" or "WideResNet-28-10-torchdistill" or "WideResNet-28-10-xternalz"
dropout: 0.3

# Optimizer
lr: 0.1
momentum: 0.9
weight_decay: 2.0e-4
lr_decay: 0.01
lr_decay_epochs: [160, 180]
enable_linear_warmup: False

# Logging
disable_wandb: True

# Checkpoint
enable_checkpoint: False
save_ckpt_every_n_epoch: 10
load_ckpt: False
load_ckpt_filepath: "checkpoints/.pt"
load_ckpt_epoch: 0

# Training
num_epochs: 200
