# Dataloader
DATALOADER__BATCH_SIZE: 128
DATALOADER__NUM_WORKERS: 8

# Optimizer
OPTIM__LR: 0.1
OPTIM__MOMENTUM: 0.9
OPTIM__WEIGHT_DECAY: 2.0e-4

# Training Hyperparameters
N_EPOCH: 200
SAVE_CKPT_EVERY_N_EPOCH: 10
LOAD_CKPT: False
LOAD_CKPT_FILEPATH: "checkpoints/.pt"
LOAD_CKPT_EPOCH: 0
