# Dataset
dataset: "CelebA-5" # "CIFAR-10-LT" or "CelebA-5"
train_transform_reprs:
- "RandomHorizontalFlip()"
- "RandomCrop(32, padding=4)"
- "ToTensor()"
- "Normalize((0.5037, 0.4335, 0.3993), (0.3116, 0.2951, 0.2953))"
valid_transform_reprs:
- "ToTensor()"
- "Normalize((0.5037, 0.4335, 0.3993), (0.3116, 0.2951, 0.2953))"

# DataLoader
num_workers: 8
batch_size: 128
enable_oversampling: False
oversampling_start_epoch: 30
oversample_num_majority_class_samples: True
oversample_ldam_weights: False

# Model
model: "ResNet-32-m2m" # "ResNet-32-m2m" or "ResNet-32-akamaster" or "WideResNet-28-10-torchdistill" or "WideResNet-28-10-xternalz"
dropout_rate: 0.3

# Optimizer
lr: 0.1
momentum: 0.9
weight_decay: 2.0e-4
lr_decay: 0.1
lr_decay_epochs: [30, 60]
enable_linear_warmup: False

# Logging
enable_wandb: False

# Checkpoint
enable_checkpoint: False
save_ckpt_every_n_epoch: 10
load_ckpt: False
load_ckpt_filepath: "checkpoints/.pt"
load_ckpt_epoch: 0

# Training
num_epochs: 90

# OPeN
enable_open: False
delta: 0.333333333333333333333333333333333333
pure_noise_mean: [0.5037, 0.4335, 0.3993]
pure_noise_std: [0.3116, 0.2951, 0.2953]
pure_noise_image_size: 32
open_start_epoch: 50

# Debugging
debug_run: False
