# Dataset
dataset: "CIFAR-10" #  "CIFAR-10-LT" or "CelebA-5" or "CIFAR-10"
train_transform_reprs:
- "RandomHorizontalFlip()"
- "RandomCrop(32, padding=4)"
- "ToTensor()"
valid_transform_reprs:
- "ToTensor()"

# Mean and std for normalization
normalize_mean: [0.4914, 0.4822, 0.4465]
normalize_std: [0.2023, 0.1994, 0.2010]

# DataLoader
num_workers: 8
batch_size: 128
enable_oversampling: False
oversampling_start_epoch:
oversample_majority_class_num_samples:
oversample_use_effective_num_sample_weights:
enable_pin_memory: False

# Model
model: "WideResNet-28-10-torchdistill" # "ResNet-32-akamaster" or "WideResNet-28-10-torchdistill"
dropout_rate: 0.3

# Optimizer
lr: 0.001
momentum: 0.9
weight_decay: 2.0e-4
enable_lr_decay: False
lr_decay: 
lr_decay_epochs: 
enable_linear_warmup: False
use_adam: True
adam_betas: [0.9, 0.999]

# Logging
enable_wandb: True
wandb_entity: "mlrc-pure-noise"
wandb_project: "pure-noise"
wandb_name: ""

# Checkpoint
save_ckpt: True
save_ckpt_epochs: [159, 199]
load_ckpt: False
load_ckpt_filepath: "checkpoints/.pt"

# Training
num_epochs: 200

# OPeN
enable_open: False
# delta: 0.333333333333333333333333333333333333
pure_noise_mean: [0.4914, 0.4822, 0.4465]
pure_noise_std: [0.2023, 0.1994, 0.2010]
pure_noise_image_size: 32
open_start_epoch: 160
enable_replace_with_fixed_ratio_pure_noise: True
noise_ratio: 0.25

# BN
noise_bn_option: DARBN

# Debugging
debug_run: False